version: '3.8'

services:

  ssdd-frontend:
    build:
      context: ./frontend
    ports:
      - "5010:5010"
    env_file: sql.env
    environment:
      - FLASK_APP=app/app.py
      - FLASK_DEBUG=true
      - PORT=5010
    depends_on:
      db-mysql:
        condition: service_healthy

  ssdd-llamachat:
    image: dsevilla/ssdd-llamachat:1.0
    ports:
      - "5020:5020"

  db-mysql:
    build:
      context: ./db-mysql
    ports:
      - "3306:3306"
    env_file: sql.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 7
      start_period: 20s

  backend-rest:
    build:
      context: ./backend-rest/es.um.sisdist.backend.Service
    ports:
      - "8080:8080"
    env_file: sql.env
    depends_on:
      db-mysql:
        condition: service_healthy

  backend-grpc:
    build:
      context: ./backend-grpc/es.um.sisdist.backend.grpc.GrpcServiceImpl
    ports:
      - "50051:50051"
    env_file: sql.env
    depends_on:
      db-mysql:
        condition: service_healthy

  backend-rest-externo:
    build:
      context: ./backend-rest-externo
    ports:
      - "8180:8180"
    depends_on:
      - backend-grpc
